AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for GPU testing with Plenoxels
Transform: AWS::Serverless-2016-10-31
Resources:
  # S3
  Bucket:
    Type: AWS::S3::Bucket
Outputs:
  outBucket:
    Value: !Ref Bucket